const ALBUMS = [
  {
    title: 'Master of Puppets',
    artist: 'Metallica',
    genre: 'Metal',
    release_year: 1986,
    price: 24.99,
    stock: 12,
    description: 'Thrash metal landmark recorded in Copenhagen and still the gateway album for a generation of metal listeners.',
    cover_image_url: 'https://picsum.photos/seed/masterofpuppets/600/600',
  },
  {
    title: 'The Number of the Beast',
    artist: 'Iron Maiden',
    genre: 'Metal',
    release_year: 1982,
    price: 22.5,
    stock: 8,
    description: 'NWOBHM classic that introduced Bruce Dickinson and defined Iron Maiden’s 1980s sound.',
    cover_image_url: 'https://picsum.photos/seed/numberofthebeast/600/600',
  },
  {
    title: 'Paranoid',
    artist: 'Black Sabbath',
    genre: 'Metal',
    release_year: 1970,
    price: 21.0,
    stock: 10,
    description: 'Foundational heavy metal record: riffs, doom, and working-class dread from Birmingham.',
    cover_image_url: 'https://picsum.photos/seed/paranoid/600/600',
  },
  {
    title: 'Reign in Blood',
    artist: 'Slayer',
    genre: 'Metal',
    release_year: 1986,
    price: 19.99,
    stock: 6,
    description: 'A 29-minute thrash assault produced by Rick Rubin; still the genre’s speed limit.',
    cover_image_url: 'https://picsum.photos/seed/reigninblood/600/600',
  },
  {
    title: 'Kind of Blue',
    artist: 'Miles Davis',
    genre: 'Jazz',
    release_year: 1959,
    price: 27.5,
    stock: 15,
    description: 'Modal jazz masterpiece and one of the best-selling jazz albums of all time.',
    cover_image_url: 'https://picsum.photos/seed/kindofblue/600/600',
  },
  {
    title: 'A Love Supreme',
    artist: 'John Coltrane',
    genre: 'Jazz',
    release_year: 1965,
    price: 26.0,
    stock: 7,
    description: 'Four-part spiritual suite that remains the high-water mark of 1960s jazz devotion.',
    cover_image_url: 'https://picsum.photos/seed/alovesupreme/600/600',
  },
  {
    title: 'Time Out',
    artist: 'Dave Brubeck Quartet',
    genre: 'Jazz',
    release_year: 1959,
    price: 18.75,
    stock: 9,
    description: 'Unusual time signatures made friendly: Take Five turned odd meters into a hit single.',
    cover_image_url: 'https://picsum.photos/seed/timeout/600/600',
  },
  {
    title: 'Head Hunters',
    artist: 'Herbie Hancock',
    genre: 'Jazz',
    release_year: 1973,
    price: 20.0,
    stock: 11,
    description: 'Jazz-funk crossover that put synthesizers and the Headhunters groove on the map.',
    cover_image_url: 'https://picsum.photos/seed/headhunters/600/600',
  },
  {
    title: 'Abbey Road',
    artist: 'The Beatles',
    genre: 'Rock',
    release_year: 1969,
    price: 29.99,
    stock: 20,
    description: 'The Beatles’ last recorded album: medley side, Moog experiments, and that zebra crossing.',
    cover_image_url: 'https://picsum.photos/seed/abbeyroad/600/600',
  },
  {
    title: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    genre: 'Rock',
    release_year: 1973,
    price: 28.5,
    stock: 14,
    description: 'Concept album about time, money, and madness that lived on the Billboard chart for years.',
    cover_image_url: 'https://picsum.photos/seed/darkside/600/600',
  },
  {
    title: 'Nevermind',
    artist: 'Nirvana',
    genre: 'Rock',
    release_year: 1991,
    price: 23.0,
    stock: 16,
    description: 'The record that pulled alternative rock into the mainstream without sanding off the noise.',
    cover_image_url: 'https://picsum.photos/seed/nevermind/600/600',
  },
  {
    title: 'OK Computer',
    artist: 'Radiohead',
    genre: 'Rock',
    release_year: 1997,
    price: 22.0,
    stock: 13,
    description: 'Paranoid, beautifully arranged millennial anxiety — still the template for ambitious guitar albums.',
    cover_image_url: 'https://picsum.photos/seed/okcomputer/600/600',
  },
  {
    title: 'Illmatic',
    artist: 'Nas',
    genre: 'Hip-Hop',
    release_year: 1994,
    price: 21.5,
    stock: 9,
    description: 'Queensbridge coming-of-age: compact, cinematic, and still the east-coast lyric standard.',
    cover_image_url: 'https://picsum.photos/seed/illmatic/600/600',
  },
  {
    title: 'The Low End Theory',
    artist: 'A Tribe Called Quest',
    genre: 'Hip-Hop',
    release_year: 1991,
    price: 20.99,
    stock: 8,
    description: 'Jazz-rap chemistry between Q-Tip, Phife, and a double-bass-heavy boom-bap pocket.',
    cover_image_url: 'https://picsum.photos/seed/lowendtheory/600/600',
  },
  {
    title: 'To Pimp a Butterfly',
    artist: 'Kendrick Lamar',
    genre: 'Hip-Hop',
    release_year: 2015,
    price: 24.0,
    stock: 18,
    description: 'Funk, jazz, and politics braided into a statement album of the 2010s.',
    cover_image_url: 'https://picsum.photos/seed/tpab/600/600',
  },
  {
    title: 'Thriller',
    artist: 'Michael Jackson',
    genre: 'Pop',
    release_year: 1982,
    price: 19.5,
    stock: 22,
    description: 'The pop production peak of the early MTV era, from Billie Jean to the title-track mini-movie.',
    cover_image_url: 'https://picsum.photos/seed/thriller/600/600',
  },
  {
    title: 'Like a Prayer',
    artist: 'Madonna',
    genre: 'Pop',
    release_year: 1989,
    price: 17.99,
    stock: 10,
    description: 'Personal, gospel-tinged pop that closed the 1980s with Madonna’s most adventurous writing.',
    cover_image_url: 'https://picsum.photos/seed/likeaprayer/600/600',
  },
  {
    title: 'Lemonade',
    artist: 'Beyoncé',
    genre: 'Pop',
    release_year: 2016,
    price: 25.0,
    stock: 12,
    description: 'A visual album weaving R&B, rock, and Southern history into a narrative of betrayal and repair.',
    cover_image_url: 'https://picsum.photos/seed/lemonade/600/600',
  },
  {
    title: 'Discovery',
    artist: 'Daft Punk',
    genre: 'Electronic',
    release_year: 2001,
    price: 23.5,
    stock: 14,
    description: 'Filter-house and sample collage that turned robot helmets into a global pop language.',
    cover_image_url: 'https://picsum.photos/seed/discovery/600/600',
  },
  {
    title: 'Selected Ambient Works 85-92',
    artist: 'Aphex Twin',
    genre: 'Electronic',
    release_year: 1992,
    price: 26.5,
    stock: 5,
    description: 'Bedroom techno that still sounds like it arrived from a parallel 1990s.',
    cover_image_url: 'https://picsum.photos/seed/saw85/600/600',
  },
  {
    title: 'Homogenic',
    artist: 'Björk',
    genre: 'Electronic',
    release_year: 1997,
    price: 21.25,
    stock: 7,
    description: 'Strings collide with beats: Icelandic art-pop at its most volcanic and precise.',
    cover_image_url: 'https://picsum.photos/seed/homogenic/600/600',
  },
  {
    title: 'London Calling',
    artist: 'The Clash',
    genre: 'Punk',
    release_year: 1979,
    price: 24.25,
    stock: 11,
    description: 'Double album that stretched punk into reggae, rockabilly, and late-empire dread.',
    cover_image_url: 'https://picsum.photos/seed/londoncalling/600/600',
  },
  {
    title: "What's Going On",
    artist: 'Marvin Gaye',
    genre: 'Soul',
    release_year: 1971,
    price: 22.75,
    stock: 9,
    description: 'A suite about war, ecology, and inner cities that redefined what a Motown album could be.',
    cover_image_url: 'https://picsum.photos/seed/whatsgoingon/600/600',
  },
  {
    title: 'Blue',
    artist: 'Joni Mitchell',
    genre: 'Folk',
    release_year: 1971,
    price: 23.99,
    stock: 8,
    description: 'Confessional songwriting distilled to piano, dulcimer, and unguarded voice.',
    cover_image_url: 'https://picsum.photos/seed/joniblue/600/600',
  },
];

module.exports = { ALBUMS };
